apiVersion: v1
kind: Service
metadata:
  name     : ntp
  namespace: work
spec:
  type: NodePort
  ports:
    - name: http
      port: 8085 #服务端口
      protocol: TCP
      targetPort: 8085 #容器内端口
      nodePort: 32423 #向外暴漏端口
  selector:
    app: ntp
  sessionAffinity: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntp
  namespace: work
  labels:
    app: ntp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ntp
  template:
    metadata:
      labels:
        app: ntp
    spec:
      imagePullSecrets:
        - name: work-secret

      # nodeSelector:
      #   slave: "183"  #部署到固定节点上
      containers:
        - name: ntp
          image: dockerhub.hobbszhou.cn/services/ntp:v1.1
          imagePullPolicy: IfNotPresent
#          command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
          ports:
            - containerPort: 8085
          env:
            - name: IDC
              value: dev #dev 开启swagger