// Code generated by goctl. DO NOT EDIT.
package types

type NtpInfoReq struct {
	Time_zone       string `json:"time_zone"`       // 时区
	Ntp_remote_addr string `json:"ntp_remote_addr"` // ntp远端同步的服务端地址，自建ntp通过这个地址同步
}

type NtpInfoRep struct {
	Time_zone []string `json:"time_zone"`
	Ntp_time  string   `json:"ntp_time"`
}
