// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"ntp_server/cmd/api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Cors},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/ntp/ntpInfo",
					Handler: GetNtpInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/ntp/ntpServer",
					Handler: CreateNtpServerHandler(serverCtx),
				},
			}...,
		),
	)
}
